extends: eslint-config-airbnb
parser: babel-eslint
plugins:
  - babel
env:
  es6: true
  mocha: true
  node: true
globals:
  web3: true
  artifacts: true
  contract: true
rules:
  max-len:
    - error
    - 100
  no-use-before-define: 0
  import/prefer-default-export: 0
  no-await-in-loop: 0
  class-methods-use-this: 0
